### ISSUE TITLE
kaminrariのページャライズ、Truncateって出てくるのどういう意味

### ISSUE THREAD

**Issue by kassy916** [kassy916/Test#298]
## エラー内容
kaminariのページャライズでTruncateと出てくる
<img width="440" alt="2018-11-03 2 59 59" src="https://user-images.githubusercontent.com/34521597/47932307-a4ade580-df14-11e8-8dcc-d885aa9acff8.png">

## エラー原因
Truncateは「省略」みたいな意味。翻訳ファイル(ja.yml)で定義してあげないとそのまま出ちゃう。

### config > locales > ja.yml
truncateの翻訳語を定義する
```
  views:
    pagination:
      next: "»"
      previous: "«"
      first: "« 最初"
      last: "最後 »"
      truncate: "..."
```

## 参考URL
- [kaminari で truncate を定義し忘れると Truncate って表示される](https://kakakakakku.hatenablog.com/entry/2014/05/01/225207)

## 参考資料
添付ファイルを参照（ある場合は）
